import numpy as np
import cv2 as cv

print(cv.getStructuringElement(cv.MORPH_ELLIPSE, (7, 7)))
print(cv.getStructuringElement(cv.MORPH_CROSS, (7, 7)))
print(cv.getStructuringElement(cv.MORPH_RECT, (7, 7)))
img = cv.imread("../images/smarties.jpg", 0)
img = cv.resize(img, (500, 300))
_, th = cv.threshold(img, 120, 255, cv.THRESH_BINARY)
kernel = np.ones((4, 4), np.uint8)
erosion = cv.erode(th, kernel)
dilation = cv.dilate(th, kernel)
opening = cv.morphologyEx(th, cv.MORPH_OPEN, kernel, anchor=(1, 2), borderType=cv.BORDER_REFLECT)
closing = cv.morphologyEx(th, cv.MORPH_CLOSE, kernel, anchor=(1, 2), borderType=cv.BORDER_REFLECT)
gradient = cv.morphologyEx(th, cv.MORPH_GRADIENT, kernel, anchor=(1, 2), borderType=cv.BORDER_REFLECT)
topHat = cv.morphologyEx(th, cv.MORPH_TOPHAT, kernel, anchor=(1, 2), borderType=cv.BORDER_REFLECT)
blackHat = cv.morphologyEx(th, cv.MORPH_BLACKHAT, kernel, anchor=(1, 2), borderType=cv.BORDER_REFLECT)
# cv.imshow("original", th)
# cv.imshow("erosion", erosion)
# cv.imshow("dilation", dilation)
# cv.imshow("morph", opening)
# cv.imshow("opening", opening)
# cv.imshow("closing", closing)
# cv.imshow("gradient", gradient)
# cv.imshow("topHat", topHat)
cv.imshow("blackHat", blackHat)
cv.waitKey(0)
cv.destroyAllWindows()
